export const ACTION_TYPES = {
  FETCH_SHIPPING_INFO_REQUEST: "FETCH_SHIPPING_INFO_REQUEST",
  FETCH_SHIPPING_INFO_SUCCESS: "FETCH_SHIPPING_INFO_SUCCESS",
  FETCH_SHIPPING_INFO_FAILURE: "FETCH_SHIPPING_INFO_FAILURE",
};
